version: "3"
services:
  card-payment-backend:
    image: card-payment-backend-image
    restart: 5
    build .
    ports:
      - 8085-8095:8080
    environment:
      MYSQL_HOST: abc-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    # container_name: card-payment-backend

  abc-mysql:
    container_name: abc-mysql
    image: mysql
    ports:
    - 3307: 3306
    environment:
      MYSQL_DATABASE: paytime_db
      MYSQL_ROOT_PASSWORD: root
