apiVersion: v1
kind: Service
metadata:
  name: card-payment-service
  namespace: ravindu-lashan
spec:
  type: LoadBalancer
  selector:
    app: card-payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http